name: team_social
description: tea which is responsible for creating social interaction part of the app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  build_runner: any
  cloud_firestore: ^3.1.15
  dio: ^4.0.6
  equatable: any
  firebase_core: ^1.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed: any
  freezed_annotation: any
  get_it: ^7.2.0
  intl: ^0.17.0
  json_annotation: any
  json_serializable: any

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
