// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALEML87Yy-98KTBmrnkL4Btr_2ZEf2d-A',
    appId: '1:725941165934:web:e227edcda09801573c6b7f',
    messagingSenderId: '725941165934',
    projectId: 'newsprojectmf',
    authDomain: 'newsprojectmf.firebaseapp.com',
    storageBucket: 'newsprojectmf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoIUKLMM1UtcBDMvwGUgh6rCjTX8DE2O4',
    appId: '1:725941165934:android:c6b7289219cf40813c6b7f',
    messagingSenderId: '725941165934',
    projectId: 'newsprojectmf',
    storageBucket: 'newsprojectmf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrlqUarZgs3ontJa0D9FSZpFwiIWYnbfg',
    appId: '1:725941165934:ios:d251b5b9b53f17f03c6b7f',
    messagingSenderId: '725941165934',
    projectId: 'newsprojectmf',
    storageBucket: 'newsprojectmf.appspot.com',
    iosClientId: '725941165934-mnp7hq27n5075oas8gpp7qm1jelts7jt.apps.googleusercontent.com',
    iosBundleId: 'com.can.news-microfrontends.dev',
  );
}
